### ISSUE TITLE
NPM Install RACF results in a loop in /usr/lpp/IBM/cnj/v12r0/njsc/exe/cnjdrvr

### ISSUE THREAD

**Issue by pwelsh80** [ibmruntimes/node-racf#5]
Hi, 
I am trying to install the RACF module using npm.  The address space then looks to go on and go into a loop  - i cancelled it at ~ 2000 CPU seconds resulting in the below output.   
is this a common problem with a common solution ? 

MVST:PWQ:/u/pwq/node/nativenode: > npm install racf

> racf@1.0.6 install /u/pwq/node/nativenode/node_modules/racf
> node-gyp rebuild

make: Entering directory '/u/pwq/node/nativenode/node_modules/racf/build'
  CXX(target) Release/obj.target/racf/racf_interface.o
FSUM3224 njsc++: Fatal error in /usr/lpp/IBM/cnj/v12r0/njsc/exe/cnjdrvr: signal 9 received.
make: *** [racf.target.mk:114: Release/obj.target/racf/racf_interface.o] Error 251
make: Leaving directory '/u/pwq/node/nativenode/node_modules/racf/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lpp/IBM/cnj/v12r0/IBM/node-v12.18.0-os390-s390x/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System OS/390 27.00
gyp ERR! command "/usr/lpp/IBM/cnj/v12r0/IBM/node-v12.18.0-os390-s390x/bin/node" "/usr/lpp/IBM/cnj/v12r0/IBM/node-v12.18.0-os390-s390x/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /u/pwq/node/nativenode/node_modules/racf
gyp ERR! node -v v12.18.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm WARN nativenode@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! racf@1.0.6 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the racf@1.0.6 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by pwelsh80** [comment]
After several more attempts, i went back and used the default /etc/profile   plus the required env vars for Node, Python, Make 
The process no longer loops now.   and it looks like it builds the first 2 objects  and then fails at the linkedit. 

I am now getting the following error. 

MVST:PWQ:/u/pwq/node/nativenode: > npm install racf

> racf@1.0.6 install /u/pwq/node/nativenode/node_modules/racf
> node-gyp rebuild

make: Entering directory '/u/pwq/node/nativenode/node_modules/racf/build'
  CXX(target) Release/obj.target/racf/racf_interface.o
  CXX(target) Release/obj.target/racf/racf.o
  SOLINK_MODULE(target) Release/obj.target/racf.node
IKJ56228I DATA SET CEE.SCEEBND2 NOT IN CATALOG OR CATALOG CAN NOT BE ACCESSED
FSUM3052 The data definition name SYSLIB cannot be resolved. The data set was not found. Ensure that data set name CEE.SCEEBND2 is specified correctly.
make: *** [racf.target.mk:140: Release/obj.target/racf.node] Error 4
make: Leaving directory '/u/pwq/node/nativenode/node_modules/racf/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lpp/IBM/cnj/v12r0/IBM/node-v12.18.0-os390-s390x/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System OS/390 27.00
gyp ERR! command "/usr/lpp/IBM/cnj/v12r0/IBM/node-v12.18.0-os390-s390x/bin/node" "/usr/lpp/IBM/cnj/v12r0/IBM/node-v12.18.0-os390-s390x/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /u/pwq/node/nativenode/node_modules/racf
gyp ERR! node -v v12.18.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm WARN nativenode@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! racf@1.0.6 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the racf@1.0.6 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

_CXX_PLIB_PREFIX=SYS1,   SYS1.SCEEBND2  exists and is cataloged. 
the search continues ...

**Comment by pwelsh80** [comment]
Hi, 
So we have installed the SMP/E version of IBM Node SDK V12. (z/OS 2.4)   Looking at the docco for IBM Node,  the PAX install includes a step where you run setup.pl  and you have to supply it with LE HLQ values  (not CEE). i don't know but i guess this script modifies certain supplied default input file.   however having installed using SMP/E  - no setup.pl and no idea. 

so initially my thought was is there something in the makefile that specifies a SYSLIB concatenation  - because its NPM and it cleans up after itself on a failed install,  i don't get to see the makefile  

so i started poking around  and was playing with nsjc++ in USS.   if you run  :
MVST:PWQ:/u/pwq/node/nativenode: > njsc++ -#

you get the following output:
FSUM0000I  Utility(njsc)                     Level(D191128.N312)
exec: export(export,NJSC_CONFIG=/usr/lpp/IBM/cnj/v12r0/njsc/etc/njsc.cfg:clang++,NULL)
exec: /bin/pg(/bin/pg,/usr/lpp/IBM/cnj/v12r0/njsc/msg/C/njscd.help,NULL)

that's new,   an environment variable called NJSC_CONFIG -  that's not in the docco anywhere ?  and it points to 
/usr/lpp/IBM/cnj/v12r0/njsc/etc/njsc.cfg

what do you know, it contains the following :

* common definitions
DEFLT:        cppcomp           = /usr/lpp/IBM/cnj/v12r0/njsc/exe/cnjdrvr
              ccomp             = /usr/lpp/IBM/cnj/v12r0/njsc/exe/cnjdrvr
              as                = /bin/c89
              ld_c              = /bin/c89
              ld_cpp            = /bin/cxx
              sysobj            = cee.sceeobj:cee.sceecpp
              syslib_x          = cee.sceebnd2:sys1.csslib
              exportlist_c_x    = cee.sceelib(celhs003,celhs001)
              exportlist_cpp_x  = cee.sceelib(celhs003,celhs001,celhscpp)
              exportlist_c_64   = cee.sceelib(celqs003)
              exportlist_cpp_64 = cee.sceelib(celqs003,celqscpp,cxxrt64)
              cinc              = -isystem/usr/include/le
              cppinc            = -isystem/usr/include/c++
              options           = -D_UNIX03_WITHDRAWN,-L/usr/lpp/cbclib/lib
              libraries         = -libmcmp
              steplib           = SYS1.SCNJCMP



changing those CEE.  to SYS1.  and the module compiles successfully 

I hope this rambling journey can maybe help the next guy. 

Cheers.
